services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: brain-agriculture-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-brain_agriculture}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_NAME:-brain_agriculture}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Your Application
  brain-agriculture-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brain-agriculture-api
    restart: always
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local